
# CIS024C -  Fall 2024 - HW3

## Homework 3

Homework 3 covers exercises in basic collection objects in Python - lists and tuples.

The below sites have some interesting and useful information on these objects.

http://sthurlow.com/python/lesson06/
https://docs.python.org/2/tutorial/datastructures.html

Once you have completed all the exercises, you will need to save and upload this URL to your Canvas

**Exercise 1 - Testing your knowledge of lists and tuples**

Answer the below questions

1. Are lists mutable? Yes or No
2. Are tuples mutable? Yes or No
3. Are Strings mutable? True or False
4. If x is a tuple of the form ```x=(1,2,3)```, the operation ```x[0]=1``` is a valid operation? True or False

Your answer should be of the form
1. your response
2. your response
3. your response
4. your response

1. Yes
2. No
3. False
4. False

#### Exercise 2 -  Initializing a list and tuple

1. Initialize a list variable **myList** using square brackets with the number 10,20,30. Display the list
2. Initialize a tuple variable **myTuple** using parenthesis with the names John, Adams, Christopher. Display the tuple.

In [1]:
### YOUR CODE GOES
myList = [10, 20, 30]
print(myList)

myTuple = ("John", "Adams", "Christopher")
print(myTuple)
### END CODE

[10, 20, 30]
('John', 'Adams', 'Christopher')

#### Exercise 3 - Displaying values in a list object

Create a list object with 10 arbitrary numbers. Print from the second element to the seventh element

**Example:**

If your list has ```[2,3,4,5,6]```, then you will need to display ```[3,5]```

In [2]:
### YOUR CODE GOES BELOW
numbers = [15, 23, 8, 42, 9, 34, 56, 78, 11, 90]
print(numbers[1:7])
### END CODE

[23, 8, 42, 9, 34, 56]

#### Exercise 4 - Sorting a list of strings

Enter a list of names. Sort the names in descending order.


**Python List sort() Method**

**Example:** Sort the list alphabetically:

In [3]:
cars = ['Ford', 'BMW', 'Volvo']
cars.sort()  # sorting list alphabetically
print(cars)
cars.sort(reverse=True)  # sorting list in descending order.
print(cars)

['BMW', 'Ford', 'Volvo']
['Volvo', 'Ford', 'BMW']

#### Exercise 5 - Updating the values of a tuple

colors = ('blue', 'red', 'green', 'white', 'purple')

You want to:

1 - change the 'white' color to 'gray'

2 - add 'yellow' color to the tuple

3 - print the sorted tuple alphabetically

In [6]:
### YOUR CODE GOES BELOW
colors = ('blue', 'red', 'green', 'white', 'purple')

colors_list = list(colors)

colors_list[colors_list.index('white')] = 'gray'

colors_list.append('yellow')

colors = tuple(colors_list)

print(tuple(sorted(colors)))
### END CODE

('blue', 'gray', 'green', 'purple', 'red', 'yellow')