# CIS024C -  Spring 2024 - Lab - Week4

## Lab- Week 4

#### Exercise 1 (20 points)

Write a Python program to obtain the student score from the student. Perform the below check

* If the student’s score is < 80, mark the student as fail
* If the student’s score is greater than or equal to 80, then perform the below check in a nested elis statement
* If student score is >= 90, mark the grade as A
* If student score is greater than or equal to 80 but less than 90, mark the grade as B

In [ ]:
### YOUR CODE GOES BELOW
score = float(input("Enter the student's score: "))
if score < 80:
    print("The student has failed.")
else:
    if score >= 90:
        print("The student has passed with a grade of A.")
    else:
        print("The student has passed with a grade of B.")
### END CODE

Enter the student's score: 85
The student has passed with a grade of B.

#### Exercise 2 (20 points)

Write a Python to get the salary of three employees in an organization.

get salaries as an input for Employee_1, Employee_2, Employee_3

Check to see if any two employees have the same salary. Display an appropriate message, which one's have the same salary which slary is geater than others ... .

In [ ]:
### YOUR CODE GOES BELOW
salary_1 = float(input("Enter the salary of Employee_1: "))
salary_2 = float(input("Enter the salary of Employee_2: "))
salary_3 = float(input("Enter the salary of Employee_3: "))

if salary_1 == salary_2 and salary_1 == salary_3:
    print("All three employees have the same salary.")
elif salary_1 == salary_2:
    print("Employee_1 and Employee_2 have the same salary.")
elif salary_1 == salary_3:
    print("Employee_1 and Employee_3 have the same salary.")
elif salary_2 == salary_3:
    print("Employee_2 and Employee_3 have the same salary.")
else:
    print("No employees have the same salary.")

if salary_1 > salary_2 and salary_1 > salary_3:
    print("Employee_1 has the highest salary.")
elif salary_2 > salary_1 and salary_2 > salary_3:
    print("Employee_2 has the highest salary.")
elif salary_3 > salary_1 and salary_3 > salary_2:
    print("Employee_3 has the highest salary.")
### END CODE

Enter the salary of Employee_1: 1650
Enter the salary of Employee_2: 1650
Enter the salary of Employee_3: 2000
Employee_1 and Employee_2 have the same salary.
Employee_3 has the highest salary.

#### Exercise 3 (20 points)

Write a Python program that ask users (4 users: user_1, ...) to write their ages.

* Find the average age and print it on the screen.
* if the users have the same age print they have the same age and compare ages together and print your comparisons.

In [ ]:
### YOUR CODE GOES BELOW
age_1 = int(input("Enter the age of user_1: "))
age_2 = int(input("Enter the age of user_2: "))
age_3 = int(input("Enter the age of user_3: "))
age_4 = int(input("Enter the age of user_4: "))

average_age = (age_1 + age_2 + age_3 + age_4) / 4
print(f"The average age is: {average_age:.2f}")

if age_1 == age_2 or age_1 == age_3 or age_1 == age_4:
    print(f"user_1 has the same age as another user.")
if age_2 == age_3 or age_2 == age_4:
    print(f"user_2 has the same age as another user.")
if age_3 == age_4:
    print(f"user_3 has the same age as user_4.")

ages = [("user_1", age_1), ("user_2", age_2), ("user_3", age_3), ("user_4", age_4)]
ages.sort(key=lambda x: x[1])

print(f"{ages[3][0]} is the oldest with age {ages[3][1]}.")
print(f"{ages[0][0]} is the youngest with age {ages[0][1]}.")
### END CODE

Enter the age of user_1: 45
Enter the age of user_2: 22
Enter the age of user_3: 56
Enter the age of user_4: 43
The average age is: 41.50
user_3 is the oldest with age 56.
user_2 is the youngest with age 22.

#### Exercise 4 (20 points)

Write a Python program that ask users (4 users: name_1, ...) to write their first names.

* Check the first letter of each name and

if it is a vowel print "the first letter of name_x is a vowel"

if it is not a vowel print "the first letter of name_x is a constant"

In [ ]:
### YOUR CODE GOES BELOW
name_1 = input("Enter the first name of name_1: ")
name_2 = input("Enter the first name of name_2: ")
name_3 = input("Enter the first name of name_3: ")
name_4 = input("Enter the first name of name_4: ")

def check_first_letter(name):
    if name[0].lower() in 'aeiou':
        return f"The first letter of {name} is a vowel."
    else:
        return f"The first letter of {name} is a consonant."

print(check_first_letter(name_1))
print(check_first_letter(name_2))
print(check_first_letter(name_3))
print(check_first_letter(name_4))
### END CODE

Enter the first name of name_1: JIbran
Enter the first name of name_2: Maggie
Enter the first name of name_3: Samantha
Enter the first name of name_4: Ceci
The first letter of JIbran is a consonant.
The first letter of Maggie is a consonant.
The first letter of Samantha is a consonant.
The first letter of Ceci is a consonant.

#### Exercise 5 (20 points)


Write a Python program that ask user to choose (5 colos: color_1, ...).

Check how many colors are in dark group and how many are in light group

dark group = black, blue, brown, green, purple, red, burgendy

light color = yellow, orange, pink, creame, white, gray

Then print "color_x and ... is in light group "
also print "color_y and ... is in dark group "

In [ ]:
### YOUR CODE GOES BELOW
dark_group = {"black", "blue", "brown", "green", "purple", "red", "burgundy"}
light_group = {"yellow", "orange", "pink", "cream", "white", "gray"}

user_input = input("Enter 5 colors separated by commas: ")
colors = [color.strip().lower() for color in user_input.split(",")]

dark_colors = list(filter(lambda color: color in dark_group, colors))
light_colors = list(filter(lambda color: color in light_group, colors))

if light_colors:
    print(f"{', '.join(light_colors)} is in the light group.")
else:
    print("No colors are in the light group.")

if dark_colors:
    print(f"{', '.join(dark_colors)} is in the dark group.")
else:
    print("No colors are in the dark group.")
### END CODE

Enter 5 colors separated by commas: black,orange,green,cream,red
orange, cream is in the light group.
black, green, red is in the dark group.